version: "3.8"

services:
  nodered_flutter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodered_flutter
    ports:
      - "${NODERED_PORT:-1880}:1880"
    environment:
      - FLUTTER_VERSION=${FLUTTER_VERSION:-stable}
    volumes:
      - nodered_data:/data
      - flutter_sdk:/opt/flutter
      - flutter_cache:/root/.pub-cache
      - flutter_build:/root/build
      - android_home:/root/Android
    restart: unless-stopped

volumes:
  nodered_data:
  flutter_sdk:
  flutter_cache:
  flutter_build:
  android_home:
